# Advent of Code Solution

# Run a specific part with input from stdin
run PART:
    #!/usr/bin/env bash
    kotlinc {{PART}}.kt common.kt -include-runtime -d /tmp/aoc-{{PART}}.jar
    java -jar /tmp/aoc-{{PART}}.jar
    rm /tmp/aoc-{{PART}}.jar

# Test both parts with sample input
test:
    @echo "Testing Part 1:"
    @just run part1 < sample.txt
    @echo "\nTesting Part 2:"
    @just run part2 < sample.txt

# Format code
format:
    ktlint -F *.kt
