import { describe, test } from "node:test";
import assert from "node:assert";
import { solvePart1, solvePart2 } from "./common.js";

const sampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe("Part 1", () => {
  test("should solve sample input correctly", () => {
    const result = solvePart1(sampleInput);
    assert.strictEqual(result, 21);
  });
});

describe("Part 2", () => {
  test("should solve sample input correctly", () => {
    const result = solvePart2(sampleInput);
    assert.strictEqual(result, 40);
  });
});
